name: build-and-deploy

on:
  push:
    branches: [feature/3978-deploy-pipeline]
  pull_request:
    branches: [feature/3978-deploy-pipeline]
  release:
    types: [published]
  workflow_dispatch:

env:
  DOCKER_HUB_ORGANISATION: rtgsglobal

jobs:
  build:
    name: build-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & run tests
        run: docker build packages/client --target build
  publish-to-docker-dev:
    name: publish-to-docker-dev
    if: ${{ github.ref == 'refs/heads/feature/3978-deploy-pipeline' }}
    needs: build
    env:
      DOCKER_HUB_REPO: bank-portal-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ env.DOCKER_HUB_REPO }}
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: packages/client
          push: true
          tags: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ env.DOCKER_HUB_REPO }}:${{ github.run_number }}
