name: build-and-deploy

on:
  push:
    branches: [feature/3978-deploy-pipeline]
  pull_request:
    branches: [feature/3978-deploy-pipeline]
  release:
    types: [published]
  workflow_dispatch:

env:
  DOCKER_HUB_ORGANISATION: rtgsglobal

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & run client tests
        run: docker build packages/client --target build
      - name: Build & run server tests
        run: docker build packages/server --target build
  publish-to-docker-client-dev:
    name: publish-to-docker-client-dev
    if: ${{ github.ref == 'refs/heads/feature/3978-deploy-pipeline' }}
    needs: build
    env:
      DOCKER_HUB_REPO: bank-portal-client-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ env.DOCKER_HUB_REPO }}
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push client Docker image
        uses: docker/build-push-action@v2
        with:
          context: packages/client
          push: true
          tags: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ env.DOCKER_HUB_REPO }}:${{ github.run_number }}
  publish-to-docker-server-dev:
    name: publish-to-docker-server-dev
    if: ${{ github.ref == 'refs/heads/feature/3978-deploy-pipeline' }}
    needs: build
    env:
      DOCKER_HUB_REPO: bank-portal-server-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ env.DOCKER_HUB_REPO }}
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push server Docker image
        uses: docker/build-push-action@v2
        with:
          context: packages/server
          push: true
          tags: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ env.DOCKER_HUB_REPO }}:${{ github.run_number }}
  trigger-devops-pipeline:
    name: trigger-devops-pipeline
    if: ${{ github.ref == 'refs/heads/feature/3978-deploy-pipeline' }}
    runs-on: ubuntu-latest
    needs: [publish-to-docker-client-dev, publish-to-docker-server-dev]
    steps:
      - name: Azure Pipelines Action
        # The following does need to be 1.2 (or later) otherwise the azure-pipeline-variables are not passed to the pipeline.
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: ${{ secrets.AZURE_DEVOPS_PROJECT_URL }}
          azure-pipeline-name: ${{ secrets.AZURE_DEVOPS_BANK_PORTAL_DEPLOYMENT_PIPELINE }}
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          azure-pipeline-variables: '{"BankPortalVersion": "${{ github.run_number }}"}'
